ecommerce/Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('product.urls', namespace='product')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('comments/', include('comments.urls', namespace='comments')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import ContactUsView
app_name = 'core'

urlpatterns = [
    path('about/', TemplateView.as_view(template_name='core/about.html'), name='about'),
    path('connect_us/', ContactUsView.as_view(), name='contact_us'),

]

ecommerce/customers/urls.py
from django.urls import path, include
from .api_urls import router
from .views import *

app_name = 'customers'

urlpatterns = [
    path('register/', CustomerRegisterView.as_view(), name='customer_register'),
    path('login/', CustomerLoginView.as_view(), name='customer_login'),
    path('logout/', CustomerLogoutView.as_view(), name='customer_logout'),

    # Password Reset
    path('reset/', UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Dashboard URLs
    path('profile/', CustomerProfileView.as_view(), name='customer_profile'),
    path('dashboard/orders/', DashboardOrdersView.as_view(), name='dashboard_orders'),
    path('dashboard/addresses/', DashboardAddressView.as_view(), name='dashboard_addresses'),
    path('dashboard/user_info/', DashboardUserInfoView.as_view(), name='dashboard_user_info'),
    path('dashboard/user_info/change_password', ChangePasswordView.as_view(), name='change_password_user_info'),


    path('api/', include(router.urls)),
]

ecommerce/customers/models.py
from django.db import models
from core.models import User
from django.utils.translation import gettext as _
from core.models import BaseModel
from utils.utils import user_avatar_path


class Customer(models.Model):
    """
        A class used to implement customers
    """
    user = models.OneToOneField(User, on_delete=models.RESTRICT, verbose_name=_('User'))
    gender = models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other'), ], verbose_name=_('Gender'))
    avatar = models.FileField(upload_to=user_avatar_path, verbose_name=_('Avatar'), null=True,
                              blank=True, default='customers/images/default_avatar.jpg')

    def get_current_orders(self):
        """
        return active carts (open carts)
        """
        return self.carts.filter(is_active=True)

    def get_finished_orders(self):
        """
            return finished carts
        """
        return self.carts.filter(is_active=False)

    class Meta:
        verbose_name = _('Customer')
        verbose_name_plural = _('Customers')

    def __str__(self):
        return self.user.username


class Address(BaseModel):
    """
        A class used to implement customers
    """
    state = models.CharField(max_length=50, verbose_name=_('State'))
    city = models.CharField(max_length=50, verbose_name=_('City'))
    postal_code = models.IntegerField(verbose_name=_('Postal Code'), unique=True)
    address_detail = models.TextField(verbose_name=_('Address Detail'))
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='addresses',
                                 verbose_name=_('Customer'))

    class Meta:
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')

    def __str__(self):
        return f'{self.state} - {self.city} - {self.postal_code}'

ecommerce/customers/forms.py
from django import forms
from django.core.exceptions import ValidationError
from core.models import User
from django.utils.translation import gettext as _
from customers.models import Address, Customer


class CustomerRegistrationForm(forms.Form):
    GENDER_CHOICES = [('0', _('select your gender')), ('1', _('Male')), ('2', _('Female')), ('3', _('Other'))]

    phone = forms.CharField(max_length=13,
                            widget=forms.TextInput(
                                attrs={'class': 'form-control', 'type': 'tel', 'placeholder': _('phone')}))
    email = forms.EmailField(max_length=100,
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': _('Email')}),
                           )
    gender = forms.ChoiceField(choices=GENDER_CHOICES,
                               widget=forms.Select(attrs={'class': 'form-select mb-3', 'placeholder': 'Gender'}))

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    confirm_password = forms.CharField(label=_('confirm password'),
                                       widget=forms.PasswordInput(
                                           attrs={'class': 'form-control', 'placeholder': _('confirm password')}))

    def clean_phone(self):
        """
        stop repetitious phone number
        """
        phone = self.cleaned_data['phone']
        user = User.objects.filter(username=phone).exists()
        if user:
            raise ValidationError(_('User with this phone number already exists!'))
        return phone

    def clean_email(self):
        """
        stop repetitious email
        """
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('Email already exists!')
        return email

    def clean(self):
        """
        Check that passwords are the same
        """
        cd = super().clean()
        p1 = cd.get('password')
        p2 = cd.get('confirm_password')

        if p1 and p2 and p1 != p2:
            raise ValidationError(_('passwords does not match!'))


class CustomerLoginForm(forms.Form):
    phone = forms.CharField(max_length=100, label=_('Phone Number'),
                            widget=forms.TextInput(
                                attrs={'placeholder': _('phone number or email'), 'class': 'form-control'}))
    password = forms.CharField(label=_('Password'),
                               widget=forms.PasswordInput(
                                   attrs={'placeholder': _('your password'), 'class': 'form-control'}))


class AddressRegisterForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ("state", 'city', 'postal_code', 'address_detail',)
        exclude = ('customer',)


class CustomerEditProfileForm(forms.Form):
    GENDER_CHOICES = [('0', _('select your gender')), ('1', _('Male')), ('2', _('Female')), ('3', _('Other'))]

    avatar = forms.FileField()
    first_name = forms.CharField(label=_('First Name'), max_length=150, required=False)
    last_name = forms.CharField(label=_('Last Name'), max_length=150, required=False)
    email = forms.EmailField(label=_('Email'))
    phone_number = forms.CharField(label=_('Phone Number'), max_length=13, widget=forms.TextInput(
        attrs={'type': 'tel', 'placeholder': _('Phone Number')}))
    gender = forms.ChoiceField(choices=GENDER_CHOICES,
                               widget=forms.Select(attrs={'placeholder': 'Gender', 'class': 'form-control'}))

    def __init__(self, customer, *args, **kwargs):
        self.customer = Customer.objects.get(id=customer.id)
        super(CustomerEditProfileForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        """
        stop repetitious email
        """
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email)
        if self.customer.user != user.first():
            if user.exists():
                raise ValidationError('Email already exists!')
        return email

    def clean_phone_number(self):
        """
        stop repetitious email
        """
        phone_number = self.cleaned_data['phone_number']
        user = User.objects.filter(phone=phone_number)

        if self.customer.user != user.first():
            if user.exists():
                raise ValidationError(_('Phone Number already exists!'))
        return phone_number


class CustomerChangePassword(forms.Form):
    password = forms.CharField(label=_('Password'), widget=forms.PasswordInput(attrs={'placeholder': _('Password')}))
    confirm_password = forms.CharField(label=_('Confirm Password'),
                                       widget=forms.PasswordInput(attrs={'placeholder': _('Confirm password')}))

    def clean(self):
        """
        Check that passwords are the same
        """
        cd = super().clean()
        p1 = cd.get('password')
        p2 = cd.get('confirm_password')

        if p1 and p2 and p1 != p2:
            raise ValidationError(_('Passwords does not match!'))

ecommerce/customers/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from core.models import User
from utils.cart import Cart
from .forms import CustomerRegistrationForm, CustomerLoginForm, CustomerEditProfileForm, CustomerChangePassword
from .models import Customer
from django.utils.translation import gettext as _
from utils.client import remove_cookie


class CustomerRegisterView(View):
    """register customer view"""
    template_name = 'customers/register.html'
    form_class = CustomerRegistrationForm
    data = {
        'title': 'Register',
        'form': form_class
    }

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('product:landing')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, self.data)

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            new_user = User.objects.create_user(phone=cd['phone'], email=cd['email'], password=cd['password'])
            Customer.objects.create(user=new_user, gender=cd['gender'])
            messages.success(request, 'Registered successfully !', 'success')
            return redirect('customers:customer_login')

        # Handle Invalid form
        self.data['form'] = form
        return render(request, self.template_name, self.data)


class CustomerLoginView(View):
    template_name = 'customers/login.html'
    form_class = CustomerLoginForm
    data = {
        'title': _('Login'),
        'form': form_class
    }

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('product:landing')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, self.data)

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, phone=cd['phone'], password=cd['password'])
            if user.is_staff:
                messages.error(request, _('Your are not a Customer'), 'warning')
                return redirect('customers:customer_login')
            if user is not None:
                login(request, user)

                cart = Cart(request)
                cart.register_in_db(request)  # Register items in cookie in db
                response = remove_cookie(redirect('product:landing'), 'cart')  # del cart cookie

                # messages.success(request, _('logged in successfully'), 'success')
                if self.next:
                    return remove_cookie(redirect(self.next), 'cart')

                return response
            # Handle invalid username or password
            messages.error(request, _('Username or Password is Incorrect'), 'warning')

        # Handle Invalid form
        self.data['form'] = form
        return render(request, self.template_name, self.data)


class CustomerLogoutView(LoginRequiredMixin, View):
    """user logout view"""

    def get(self, request):
        logout(request)
        # del cart cookie on logout
        response = remove_cookie(redirect('product:landing'), 'cart')
        return response


class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = 'customers/password_reset/password_reset_form.html'
    success_url = reverse_lazy('customers:password_reset_done')
    email_template_name = 'customers/password_reset/password_reset_email.html'


class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'customers/password_reset/password_reset_done.html'


class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'customers/password_reset/password_reset_confirm.html'
    success_url = reverse_lazy('customers:password_reset_complete')


class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'customers/password_reset/password_reset_complete.html'


class CustomerProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'customers/dashboard/dashboard.html'


class DashboardOrdersView(LoginRequiredMixin, TemplateView):
    template_name = 'customers/dashboard/orders/orders.html'


class DashboardAddressView(LoginRequiredMixin, TemplateView):
    template_name = 'customers/dashboard/addresses/addresses.html'


class DashboardUserInfoView(LoginRequiredMixin, TemplateView):
    template_name = 'customers/dashboard/user_info/user_info.html'
    form_class = CustomerEditProfileForm
    form_class1 = CustomerChangePassword

    def get_context_data(self):
        context = super().get_context_data()
        context['form'] = self.form_class(self.request.user.customer,
                                          initial={'email': self.request.user.email,
                                                   'first_name': self.request.user.first_name,
                                                   'last_name': self.request.user.last_name,
                                                   'phone_number': self.request.user.phone,
                                                   'gender': self.request.user.customer.gender})
        context['cp_form'] = self.form_class1()
        return context

    def post(self, request):
        form = self.form_class(request.user.customer, request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            customer = request.user.customer
            customer.gender = cd['gender']
            customer.avatar = request.FILES.get('avatar')
            user = request.user
            user.email = cd['email']
            user.first_name = cd['first_name']
            user.last_name = cd['last_name']
            user.phone = cd['phone_number']
            user.save()
            customer.save()
            messages.success(request, _('Personal Information Updated!'), 'success personal_info')
            return redirect('customers:dashboard_user_info')
        # Handle Invalid Form
        messages.error(request, _('Please correct Below Errors!'), 'error')
        return render(request, self.template_name, {'form': form, 'cp_form': self.form_class1()})


class ChangePasswordView(LoginRequiredMixin, View):
    form_class = CustomerChangePassword
    form_class1 = CustomerEditProfileForm

    template_name = 'customers/dashboard/user_info/user_info.html'

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            request.user.set_password(cd['password'])
            request.user.save()
            messages.success(request, _('Password successfully Updated!'), 'success change_password')
            return redirect('customers:dashboard_user_info')
        # Handle Invalid Form
        messages.error(request, _('Please correct Below Errors!'), 'error change_password')
        initial = {'email': request.user.email,
                   'first_name': request.user.first_name,
                   'last_name': request.user.last_name,
                   'phone_number': request.user.phone,
                   'gender': request.user.customer.gender}
        return render(request, self.template_name,
                      {'cp_form': form, 'form': self.form_class1(request.user.customer, initial=initial)})

ecommerce/customers/templates/customers/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    {% block extra_head %}
    {% endblock %}
</head>
<body>
    <script type="text/javascript">
    //Auto-exported site-wide settings
        {% autoescape off %}var site_settings = {{ settings|safe|default:"{}" }};{% endautoescape %}
    </script>
    {% include 'inc/auth_nav.html' %}
    {% include 'inc/messages.html' %}
    {% block content %}
    {% endblock %}


    <!-- Jquery CDN -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<!-- AJAX CDN -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- Bootstrap JS CDN -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>


    <script>

        var alertList = document.querySelectorAll('.alert')
        alertList.forEach(function (alert) {
            new bootstrap.Alert(alert)
        })

        // fade alert box auto
        $(document).ready(function() {
            if ( $(".fade").css('display') !== 'none'){
                $(".fade").delay(2000).fadeOut(700)
            }
    });
    </script>
    {% block extra_footer %}
    {% endblock %}
</body>
</html>

ecommerce/customers/templates/customers/login.html
{% extends 'customers/base.html' %}
{% load i18n %}
{% block title %}
{{ title }}
{% endblock %}
{% block extra_head %}
    <style>
        form {
            box-shadow: rgba(17, 17, 26, 0.1) 0 8px 24px, rgba(17, 17, 26, 0.1) 0 16px 56px, rgba(17, 17, 26, 0.1) 0 24px 80px;

        }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid py-5" style="margin-top: 10vh;">
        <div class="row">
            <form method="post" class="col-11 col-sm-10 col-md-7 col-lg-5 col-xl-4 mx-auto p-3 rounded" novalidate>
                {{ form.non_field_errors }}

                <h1 class="fw-bold mb-2" style="font-family: 'SansSerif';color:blue;">{{ title }}</h1>
                <hr>
                {% csrf_token %}
                <div class="form-floating mb-3">
                    {{ form.phone }}
                    {{ form.phone.label_tag }}
                </div>
                 {% if form.phone.errors %}
                    {% for error in form.phone.errors %}
                        <ul>
                            <li class="text-danger">{{ error|escape }}</li>
                        </ul>
                    {% endfor %}
                {% endif %}

                <div class="form-floating mb-3">
                    {{ form.password }}
                    {{ form.password.label_tag }}
                </div>

                 {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        <ul>
                            <li class="text-danger">{{ error|escape }}</li>
                        </ul>
                    {% endfor %}
                {% endif %}
                <p><a href="{% url 'customers:reset_password' %}">{% trans 'Forget your Password?' %}</a></p>

                <input type="submit" value="{{ title }}" class="w-100 btn btn-primary p-2 mb-3 fw-bold">
                <h5 class="text-center">{% trans 'Or' %}</h5>
                <h5 class="text-center">{% trans 'If you have not an account' %} <a class="text-decoration-none" href="{% url 'customers:customer_register' %}">{% trans 'Sign Up here' %}</a></h5>
            </form>
        </div>
    </div>
{% endblock %}

ecommerce/customers/templates/customers/register.html
{% extends 'customers/base.html' %}
{% load i18n %}
{% block title %}
    {{ title }}
{% endblock %}
{% block extra_head %}
    <style>
        form {
            box-shadow: rgba(17, 17, 26, 0.1) 0 8px 24px, rgba(17, 17, 26, 0.1) 0 16px 56px, rgba(17, 17, 26, 0.1) 0 24px 80px;

        }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid py-5">
        <div class="row">
            <form method="post" class="col-11 col-sm-10 col-md-7 col-lg-5 col-xl-4 mx-auto p-3 rounded" novalidate>
                {{ form.non_field_errors }}

                <h1 class="fw-bold mb-2" style="font-family: 'SansSerif';color:blue;">{{ title }}</h1>
                <hr>
                {% csrf_token %}
                <div class="form-floating mb-3">
                    {{ form.phone }}
                    {{ form.phone.label_tag }}
                </div>
                 {% if form.phone.errors %}
                    {% for error in form.phone.errors %}
                        <ul>
                            <li class="text-danger">{{ error|escape }}</li>
                        </ul>
                    {% endfor %}
                {% endif %}
                <div class="form-floating mb-3">
                    {{ form.email }}
                    {{ form.email.label_tag }}
                </div>

                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <ul>
                            <li class="text-danger">{{ error|escape }}</li>
                        </ul>
                    {% endfor %}
                {% endif %}


                {{ form.gender }}
                {% if form.gender.errors %}
                    {% for error in form.gender.errors %}
                        <ul>
                            <li class="text-danger">{{ error|escape }}</li>
                        </ul>
                    {% endfor %}
                {% endif %}

                <div class="form-floating mb-3">
                    {{ form.password }}
                    {{ form.password.label_tag }}
                </div>

                 {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        <ul>
                            <li class="text-danger">{{ error|escape }}</li>
                        </ul>
                    {% endfor %}
                {% endif %}

                <div class="form-floating mb-3">
                    {{ form.confirm_password }}
                    {{ form.confirm_password.label_tag }}
                </div>

                {% if form.confirm_password.errors %}
                    {% for error in form.confirm_password.errors %}
                        <ul>
                            <li class="text-danger">{{ error|escape }}</li>
                        </ul>
                    {% endfor %}
                {% endif %}

                <input type="submit" value="{{ title }}" class="w-100 btn btn-primary p-2 mb-3 fw-bold">
                <h5 class="text-center">{% trans 'Or' %}</h5>
                <h5 class="text-center">{% trans 'If you Already have an account' %}? <a class="text-decoration-none" href="{% url 'customers:customer_login' %}">{% trans 'Sign in here' %}</a></h5>
            </form>
        </div>
    </div>
{% endblock %}