ecommerce/Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('product.urls', namespace='product')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('comments/', include('comments.urls', namespace='comments')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import ContactUsView
app_name = 'core'

urlpatterns = [
    path('about/', TemplateView.as_view(template_name='core/about.html'), name='about'),
    path('connect_us/', ContactUsView.as_view(), name='contact_us'),

]

ecommerce/orders/urls.py
from django.urls import path, include
from .api_urls import router
from .api_views import CartItemApiView
from .views import CartCheckOutView, PaymentView


app_name = 'orders'

urlpatterns = [
    path('api/', include(router.urls,),),
    path('api/cart_item/', CartItemApiView.as_view(), name='cart_item_api'),
    path('api/cart_item/<pk>', CartItemApiView.as_view(), name='detail_cart_item_api'),
    path('api/cart_item/<pk>/', CartItemApiView.as_view(), name='delete_cart_item'),
    path('api/cart_item/<pk>/', CartItemApiView.as_view(), name='update_cart_item'),

    path('cart/checkout/', CartCheckOutView.as_view(), name='cart_checkout'),
    path('cart/payment/', PaymentView.as_view(), name='cart_payment'),
]

ecommerce/product/urls.py
from django.urls import path, include
from .api_urls import router
from .views import *

app_name = 'product'

urlpatterns = [
    path('', LandingView.as_view(), name='landing'),
    path('product/<int:pk>/<slug:product_slug>', ProductDetailView.as_view(), name='product_detail'),
    path('category/<int:category_id>/<slug:category_slug>', CategoryDetailView.as_view(), name='category_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    # product api urls
    path('api/', include(router.urls)),

]

ecommerce/product/models.py
from django.contrib import admin
from django.db import models
from django.db.models import Max
from django.urls import reverse

from core.models import BaseModel, BaseDiscount
from django.utils.translation import gettext_lazy as _


class Product(BaseModel):
    """
        A class used to implement products
    """
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    price = models.PositiveIntegerField(default=0, verbose_name=_('Price'))
    description = models.TextField(verbose_name=_('Description'))
    inventory = models.PositiveIntegerField(verbose_name=_('Inventory'))
    slug = models.SlugField(max_length=30, help_text=_('A short label for product'), verbose_name=_('Slug'))
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE, verbose_name=_('Brand'))
    discount = models.ForeignKey('Discount', on_delete=models.CASCADE, blank=True, null=True,
                                 verbose_name=_('Discount'))
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name=_('Category'))
    final_worth = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['-created']
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    @admin.display(boolean=True)
    def is_available(self):
        return self.inventory > 0

    @property
    def final_price(self):
        """
        calculate price with discounts
        :return:
        """
        category_discount = self.category.discount.profit_value(self.price) if self.category.discount else 0
        product_discount = self.discount.profit_value(self.price) if self.discount else 0
        return self.price - (category_discount + product_discount)

    @classmethod
    def highest_price(cls):
        """
        Returns the product with the highest price
        """
        highest = cls.objects.aggregate(max_price=Max('price'))['max_price']
        return cls.objects.get(price=highest)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.final_worth = self.final_price
        super().save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        """
        make url for product
        :return: product detail page url
        """
        return reverse('product:product_detail', args=(self.id, self.slug))

    def calculate_inventory(self, count: int):
        """
        calculate and decrease product inventory
        :param count: count to decrease from inventory
        :return: remaining of product inventory
        """
        self.inventory -= count
        self.save()
        return self.inventory

    def __str__(self):
        return f'{self.name}'


class Picture(BaseModel):
    picture = models.FileField(upload_to='products/images/%Y/%m/%d/', verbose_name=_('Product Image'), null=True,
                               blank=True)
    product = models.ForeignKey(Product, on_delete=models.RESTRICT, verbose_name=_('Corresponding product'),
                                related_name=_('pictures'))

    class Meta:
        verbose_name = _('Picture')
        verbose_name_plural = _('Pictures')

    def __str__(self):
        return self.picture.url


class Brand(BaseModel):
    """
        implement brands
    """
    name = models.CharField(max_length=50, verbose_name=_('Name'), unique=True)
    country = models.CharField(max_length=50, verbose_name=_('Country'))

    class Meta:
        verbose_name = _('Brand')
        verbose_name_plural = _('Brands')

    def __str__(self):
        return self.name


class Category(BaseModel):
    """
        implement categories
    """
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    root = models.ForeignKey('self', on_delete=models.CASCADE, default=None, null=True, blank=True,
                             verbose_name=_('Parent'), related_name='children')
    discount = models.ForeignKey('Discount', on_delete=models.CASCADE, blank=True, null=True,
                                 verbose_name=_('Discount'))
    slug = models.SlugField(null=True, blank=True)
    picture = models.FileField(verbose_name=_('Category Image'), null=True, blank=True)

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _("Categories")

    def get_absolute_url(self):
        """
        make url for categories that are not root
        :return: category url
        """
        if self.root:
            return reverse('product:category_detail', args=(self.id, self.slug))
        return reverse('product:category_list')

    @property
    def get_ancestors(self):
        father = self

        ancestors = []
        while father:
            ancestors.append(father)
            father = father.root
        return ancestors[::-1]

    def __str__(self):
        return self.name


class Discount(BaseDiscount):
    """
        Implement discounts
    """

    def __str__(self):
        return f'Discount {self.value}'

ecommerce/product/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.utils.translation import gettext as _
from django.views.generic import DetailView, ListView

from comments.forms import CommentCreateForm
from product.models import Category, Product, Brand


class LandingView(ListView):
    template_name = 'product/landing/landing.html'
    model = Product
    context_object_name = 'products'
    paginate_by = 3

    def get_queryset(self):
        queryset = Product.objects.all()

        if self.request.GET.get('search'):
            queryset = queryset.filter(name__icontains=self.request.GET['search'])
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('landing')
        context['brands'] = Brand.objects.all()
        return context


class CategoryListView(ListView):
    model = Category
    template_name = 'product/category/category_list.html'
    context_object_name = 'categories'

    def get_queryset(self):
        categories = Category.objects.filter(root=None)
        return categories


class CategoryDetailView(View):
    template_name = 'product/category/category_detail.html'

    def setup(self, request, *args, **kwargs):
        self.category_instance = get_object_or_404(Category, pk=kwargs['category_id'], slug=kwargs['category_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        data = {
            'title': self.category_instance.name,
            'category_id': self.kwargs['category_id'],
            'brands': Brand.objects.all(),
            'products': Product.objects.filter(category_id=self.kwargs['category_id'])
        }
        if self.request.GET.get('search'):
            data['products'] = data['products'].filter(name__icontains=self.request.GET['search'])

        return render(request, self.template_name, data)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/product_detail.html'
    context_object_name = 'product'
    form_class = CommentCreateForm

    def setup(self, request, *args, **kwargs):
        self.product_instance = get_object_or_404(Product, pk=kwargs['pk'], slug=kwargs['product_slug'])
        self.comments = self.product_instance.pcomments.filter(is_reply=False, can_publish=True)

        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['comments'] = self.comments
        context['comment_form'] = self.form_class
        context['related_products'] = Product.objects.filter(category=self.object.category).exclude(id=self.object.id)
        return self.render_to_response(context)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        print(form.is_valid())
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user.customer
            if not request.user.first_name:
                request.user.first_name = form.cleaned_data['name']
            request.user.save()
            new_comment.product = self.product_instance
            new_comment.save()
            messages.success(request, 'thanks for your review, after admin confirmation will show')
            return redirect('product:product_detail', self.product_instance.id, self.product_instance.slug)
        context = {
            'comment_form': form,
            'comments': self.comments,
            'product': self.get_object()
        }
        return render(request, self.template_name, context)

ecommerce/product/templates/product/inc/add_to_cart.html
{% load i18n %}
<div class="flex-w flex-r-m p-b-10">

    <div class="size-204 flex-w flex-m respon6-next">
        <div class="wrap-num-product flex-w m-r-20 m-tb-10">
            <div class="btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m">
                <i class="fs-16 zmdi zmdi-minus"></i>
            </div>

            <input class="mtext-104 cl3 txt-center num-product" type="number" name="num-product" id="num-product" value="1">

            <div class="btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m">
                <i class="fs-16 zmdi zmdi-plus"></i>
            </div>
        </div>

        <!-- Add to cart button -->
        <button class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04 js-addcart-detail" id="addToCart-btn" onclick="addToCart(this.name)">
            {% trans 'Add to cart' %}
        </button>
    </div>

</div>

ecommerce/product/templates/product/inc/filter.html
<div class="dis-none panel-filter w-full p-t-10">
    <div class="wrap-filter flex-w bg6 w-full p-lr-40 p-t-27 p-lr-15-sm">
        <div class="filter-col1 p-r-15 p-b-27">
            <div class="mtext-102 cl2 p-b-15">
                Sort By
            </div>

            <ul>
                <li class="p-b-6">
                    <a href="#" class="filter-link stext-106 trans-04">
                        Default
                    </a>
                </li>

                <li class="p-b-6">
                    <a href="#" class="filter-link stext-106 trans-04">
                        Popularity
                    </a>
                </li>

                <li class="p-b-6">
                    <a href="#" class="filter-link stext-106 trans-04">
                        Average rating
                    </a>
                </li>

                <li class="p-b-6">
                    <a href="#" class="filter-link stext-106 trans-04 filter-link-active">
                        Newness
                    </a>
                </li>

                <li class="p-b-6">
                    <a href="#" class="filter-link stext-106 trans-04">
                        Price: Low to High
                    </a>
                </li>

                <li class="p-b-6">
                    <a href="#" class="filter-link stext-106 trans-04">
                        Price: High to Low
                    </a>
                </li>
            </ul>
        </div>

        <div class="filter-col2 p-r-15 p-b-27">
            <div class="mtext-102 cl2 p-b-15">
                Price
            </div>

            <ul>
                <li class="p-b-6">
                    <a href="#" class="filter-link stext-106 trans-04 filter-link-active">
                        All
                    </a>
                </li>

                <li class="p-b-6">

                    <a href="#" class="filter-link stext-106 trans-04">
                        $0.00 - $50.00
                    </a>
                </li>

                <li class="p-b-6">
                    <a href="#" class="filter-link stext-106 trans-04">
                        $50.00 - $100.00
                    </a>
                </li>

                <li class="p-b-6">
                    <a href="#" class="filter-link stext-106 trans-04">
                        $100.00 - $150.00
                    </a>
                </li>

                <li class="p-b-6">
                    <a href="#" class="filter-link stext-106 trans-04">
                        $150.00 - $200.00
                    </a>
                </li>

                <li class="p-b-6">
                    <a href="#" class="filter-link stext-106 trans-04">
                        $200.00+
                    </a>
                </li>
            </ul>
        </div>

        <div class="filter-col3 p-r-15 p-b-27">
            <div class="mtext-102 cl2 p-b-15">
                Color
            </div>

            <ul>
                <li class="p-b-6">
                    <span class="fs-15 lh-12 m-r-6" style="color: #222;">
                        <i class="zmdi zmdi-circle"></i>
                    </span>

                    <a href="#" class="filter-link stext-106 trans-04">
                        Black
                    </a>
                </li>

                <li class="p-b-6">
                    <span class="fs-15 lh-12 m-r-6" style="color: #4272d7;">
                        <i class="zmdi zmdi-circle"></i>
                    </span>

                    <a href="#" class="filter-link stext-106 trans-04 filter-link-active">
                        Blue
                    </a>
                </li>

                <li class="p-b-6">
                    <span class="fs-15 lh-12 m-r-6" style="color: #b3b3b3;">
                        <i class="zmdi zmdi-circle"></i>
                    </span>

                    <a href="#" class="filter-link stext-106 trans-04">
                        Grey
                    </a>
                </li>

                <li class="p-b-6">
                    <span class="fs-15 lh-12 m-r-6" style="color: #00ad5f;">
                        <i class="zmdi zmdi-circle"></i>
                    </span>

                    <a href="#" class="filter-link stext-106 trans-04">
                        Green
                    </a>
                </li>

                <li class="p-b-6">
                    <span class="fs-15 lh-12 m-r-6" style="color: #fa4251;">
                        <i class="zmdi zmdi-circle"></i>
                    </span>

                    <a href="#" class="filter-link stext-106 trans-04">
                        Red
                    </a>
                </li>

                <li class="p-b-6">
                    <span class="fs-15 lh-12 m-r-6" style="color: #aaa;">
                        <i class="zmdi zmdi-circle-o"></i>
                    </span>

                    <a href="#" class="filter-link stext-106 trans-04">
                        White
                    </a>
                </li>
            </ul>
        </div>

        <div class="filter-col4 p-b-27">
							<div class="mtext-102 cl2 p-b-15">
								Tags
							</div>

							<div class="flex-w p-t-4 m-r--5">
								<a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
									Fashion
								</a>

								<a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
									Lifestyle
								</a>

								<a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
									Denim
								</a>

								<a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
									Streetstyle
								</a>

								<a href="#" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
									Crafts
								</a>
							</div>
						</div>
    </div>
</div>

ecommerce/product/templates/product/inc/filter_brand.html
{% load i18n %}
<div class="flex-w flex-l-m filter-tope-group m-tb-10" id="brands">
    <button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1" data-filter="*">
        {% trans 'All Products' %}
    </button>
    {% for brand in brands %}
        <button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1" data-filter=".{{ brand.name }}">
            {{ brand.name }}
        </button>
    {% endfor %}

</div>

ecommerce/product/templates/product/inc/load_more.html
{% load i18n %}
<div class="flex-c-m flex-w w-full p-t-45">
    <a class="flex-c-m stext-101 cl5 size-103 bg2 bor1 hov-btn1 p-lr-15 trans-04" id="loadMore-btn">
        {% trans 'Load More' %}
    </a>
</div>

ecommerce/product/templates/product/inc/product_js.html
{% load static %}
{% load i18n %}
<script>
    // get all Products
    function getAllProducts() {
        $.get(
            '{% url "product:product-list" %}',
            function (data) {
                console.log(data)
            }
        )
    }

    // get all Brands
    function getAllBrands() {
        $.get(
            '{% url "product:brand-list" %}',
            function (data) {
                console.log(data)
            }
        )
    }

    // fill products section
    function products(data) {
        let products = $('#products')

        let alertEmpty = '<div class="alert alert-info mx-auto w-50 font-weight-bold text-center">Sorry There is No Item! </div>'
        if (data.count == 0) {
            products.html(alertEmpty)
        } else {
            for (let product of data.results) {
                elem = `<div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item ${product.brand}" id="${product.id}">
                <!-- Block2 -->
                <div class="block2">
                    <div class="block2-pic hov-img0">
                        <img src="${product.images[0]}" alt="${product.name}" width="200" height="300">

                        <button class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1" onclick="show_modal(${product.id})">
                            {% trans 'Quick View' %}
                        </button>
                    </div>

                    <div class="block2-txt flex-w flex-t p-t-14">
                        <div class="block2-txt-child1 flex-col-l ">
                            <a href="/product/${product.id}/${product.slug}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
                                ${product.name}
                            </a>

                            <span class="stext-105 cl3">
                                $${product.final_worth}
                            </span>
                        </div>
                        <div class="block2-txt-child2 flex-r p-t-3">
								<a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
									<img class="icon-heart1 dis-block trans-04" src="{% static 'core/images/icons/icon-heart-01.png' %}" alt="ICON">
									<img class="icon-heart2 dis-block trans-04 ab-t-l" src="{% static 'core/images/icons/icon-heart-02.png' %}" alt="ICON">
								</a>
                        </div>
                    </div>
                </div>
            </div>`
                products.append(elem)
            }
        }

    }

    // get products filtered by category
    function filterByCategory(category_id) {
        $.get(
        '{% url 'product:product-list' %}' + '?category='+ category_id,
        function (data){
            products(data)
        }
        )
    }

    // fill brands section
    function brands(data) {

        for (let b of data.results) {
            let brand = b
            elem = `<button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1" data-filter=".${brand.name}">
                    ${brand.name}
                </button>`

            $('#brands').append(elem)
        }
    }

    function show_modal(id) {
        $('.js-show-modal1').on('click', function (e) {
            e.preventDefault();
            $('.js-modal1').addClass('show-modal1');
        });

        $('.js-hide-modal1').on('click', function () {
            $('.js-modal1').removeClass('show-modal1');
        });
        getProduct(id)
    }

    // get one product
    function getProduct(productId) {
        // AJAX for Products
        let url = '{% url "product:product-detail" 0 %}'.replace('0', productId);

        $.get(
            url,
            function (data) {
                fillModal(data)
            }
        )
    }

    // fill modal
    function fillModal(data){
        let product = data
        let galleryElement = `<div class="item-slick3" data-thumb="${product.picture}">
            <div class="wrap-pic-w pos-relative">
                <img src="${product.images[0]}" alt="${product.name}" class="rounded">

                <a class="flex-c-m size-108 how-pos1 bor0 fs-16 cl10 bg0 hov-btn3 trans-04" href="${product.images[0]}">
                    <i class="fa fa-expand"></i>
                </a>
            </div>
        </div>`
        $('#modal-ProductPictures').html(galleryElement)

        $('#modal-nameProduct').text(product.name)

        // check product's discount available
        if (product.discount != null){
            $('#modal-Price').text(product.price)
        }else {
            $('#modal-Price').empty()
        }


        $('#modal-finalPrice').html(product.final_worth)
        $('#modal-description').html(product.description)
        $('#addToCart-btn').attr('name', product.id)    // set product id as name for button
        $("#num-product").attr('max', product.inventory)
    }

    // get a specific cookie
    function getCookie(cname) {
          let name = cname + "=";
          let ca = document.cookie.split(';');
          for(let i = 0; i < ca.length; i++) {
            let c = ca[i];
            while (c.charAt(0) == ' ') {
              c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
              return c.substring(name.length, c.length);
            }
          }
          return "";
        }

    // add corresponding product to cart
    function addToCart(productId){

        let cartIcon = $('.cartIcon')
        let countProduct = $('#num-product')
        // Post request for add item to cart
        $.post(
                "{% url 'orders:cart_item_api' %}",
                {
                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                    'product': productId,
                    'count': countProduct.val(),
                },

                function (data) {
                    console.log('response data of add to cart:\n',data)

                    // set cart length for cart icon on navbar
                    let cartLength = Object.keys(data.cart).length
                    cartIcon.attr('data-notify', cartLength)
                    fillCart(data)
                    swal("added to cart !",
                        {icon: "success",
                         timer: 1600,
                        buttons: false,
                    });
                }
                ).fail(function (error) {
                if (error.status == 400){
                        swal(error.responseJSON.count[0],
                            {icon: "error",
                        });
                    }
                });
    }

    // fill nav cart
     function fillCart(data){
        let item = data.item
        let cart = data.cart
        let product = data.product
        let body = $('#cartBody')
        body.find('div#emptyAlert').remove()
        let total_price = 0;

        // if product already be in cart replace it's count
        if (product.id in cart){
            console.log('already exist in cart')
            $(`#cartBody > li#${product.id}`).remove()
            item.count = cart[product.id].count
        }

            let productAbsoluteUrl = `http://127.0.0.1:8000/en/product/${product.id}/${product.slug}`
            cartItem = `<li class="header-cart-item flex-w flex-t m-b-12" id='${product.id}'>
						<div class="header-cart-item-img">
							<img src="${product.images[0]}" alt="${product.name}">
						</div>

						<div class="row header-cart-item-txt">
                            <div class="col-8 p-0">
                                <a href="${productAbsoluteUrl}" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								    ${product.name}
							    </a>

                                <span class="header-cart-item-info">
								    <span class="count-product-cart">${item.count}</span> x ${product.final_worth}
							    </span>
                            </div>

                            <div class="col-4 p-0">
                               <div>
                                    <a class="nav-removeItem-btn" data-productId="${product.id}"
                                       title="remove item">
                                        <i class="fa fa-trash text-danger p-2 rounded" aria-hidden="true"></i>
                                    </a>
                               </div>

                                {#<span class="mx-2">#}
                                {#    <a class="nav-reduceItem-btn text-danger" data-productId="${product.id}"#}
                                {#       title="reduce item">#}
                                {#        <i class="fa fa-minus" aria-hidden="true"></i>#}
                                {#    </a>#}
                                {#</span>#}

                                {#<span class="mx-2">#}
                                {#    <a class="nav-addItem-btn text-primary" data-productId="${product.id}"#}
                                {#       title="add item">#}
                                {#        <i class="fa fa-plus" aria-hidden="true"></i>#}
                                {#    </a>#}
                                {#</span>#}

                            </div>



						</div>
					</li>`

            body.append(cartItem)

        // set total price for cart
        for (i in cart){
            total_price += cart[i]['count'] * cart[i]['price']
        }
        $('#cartTotal').text(total_price)
        console.log('new price : ' + total_price)


    }

</script>

ecommerce/product/templates/product/inc/related_products.html
{% load static %}
{% load i18n %}
<section class="sec-relate-product bg0 p-t-45 p-b-105">
    <div class="container">
        <div class="p-b-45">
            <h3 class="ltext-106 cl5 txt-center">
                {% trans 'Related Products' %}
            </h3>
        </div>

        <!-- Slide2 -->
        <div class="wrap-slick2">
            <div class="slick2">
                {% for product in related_products %}
                    <div class="item-slick2 p-l-15 p-r-15 p-t-15 p-b-15">
                        <!-- Block2 -->
                        <div class="block2">

                            <div class="block2-pic hov-img0">
                                <img src="{{ product.pictures.first.picture.url }}" alt="{{ product.name }}" width="200"
                                     height="300">

                                <button
                                        class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1"
                                        onclick="show_modal({{ product.id }})">
                                    {% trans 'Quick View' %}
                                </button>
                            </div>

                            <div class="block2-txt flex-w flex-t p-t-14">

                                <div class="block2-txt-child1 flex-col-l ">

                                    <a href="{{ product.get_absolute_url }}"
                                       class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
                                        {{ product.name }}
                                    </a>

                                    <span class="stext-105 cl3">
										        ${{ product.final_worth }}
									        </span>

                                </div>

                                <div class="block2-txt-child2 flex-r p-t-3">
                                    <a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
                                        <img class="icon-heart1 dis-block trans-04"
                                             src="{% static 'core/images/icons/icon-heart-01.png' %}" alt="ICON">
                                        <img class="icon-heart2 dis-block trans-04 ab-t-l"
                                             src="{% static 'core/images/icons/icon-heart-02.png' %}" alt="ICON">
                                    </a>
                                </div>

                            </div>

                        </div>

                    </div>
                {% empty %}
                    <div class="alert alert-info w-100 mx-auto text-center">{% trans 'There is no Items' %}!</div>
                {% endfor %}

            </div>
        </div>
    </div>
</section>