ecommerce/Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('product.urls', namespace='product')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('comments/', include('comments.urls', namespace='comments')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import ContactUsView
app_name = 'core'

urlpatterns = [
    path('about/', TemplateView.as_view(template_name='core/about.html'), name='about'),
    path('connect_us/', ContactUsView.as_view(), name='contact_us'),

]

ecommerce/customers/urls.py
from django.urls import path, include
from .api_urls import router
from .views import *

app_name = 'customers'

urlpatterns = [
    path('register/', CustomerRegisterView.as_view(), name='customer_register'),
    path('login/', CustomerLoginView.as_view(), name='customer_login'),
    path('logout/', CustomerLogoutView.as_view(), name='customer_logout'),

    # Password Reset
    path('reset/', UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Dashboard URLs
    path('profile/', CustomerProfileView.as_view(), name='customer_profile'),
    path('dashboard/orders/', DashboardOrdersView.as_view(), name='dashboard_orders'),
    path('dashboard/addresses/', DashboardAddressView.as_view(), name='dashboard_addresses'),
    path('dashboard/user_info/', DashboardUserInfoView.as_view(), name='dashboard_user_info'),
    path('dashboard/user_info/change_password', ChangePasswordView.as_view(), name='change_password_user_info'),


    path('api/', include(router.urls)),
]

ecommerce/product/urls.py
from django.urls import path, include
from .api_urls import router
from .views import *

app_name = 'product'

urlpatterns = [
    path('', LandingView.as_view(), name='landing'),
    path('product/<int:pk>/<slug:product_slug>', ProductDetailView.as_view(), name='product_detail'),
    path('category/<int:category_id>/<slug:category_slug>', CategoryDetailView.as_view(), name='category_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    # product api urls
    path('api/', include(router.urls)),

]

templates/inc/nav.html
{% load i18n %}
{% load static %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
<nav class="navbar navbar-expand-lg navbar-light bg-light ">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'product:landing' %}">
            <img src="{% static 'images/logo/logo.jpg' %}" alt="logo" width="50" height="50">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'product:landing' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'product:category_list' %}">Categories</a>
                </li>


            </ul>
            <i class="bi bi-person-circle"></i>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 justify-content-end">
           {% if not request.user.is_authenticated %}

                <li class="nav-item">

                    <a class="nav-link" href="{% url 'customers:customer_login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'customers:customer_register' %}">Register</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'customers:customer_logout' %}">Logout
                    </a>

                </li>
            {% endif %}
            </ul>

             <ul class="navbar-nav">
                {% for lang in languages %}
                    <li class="nav-item">
                        <a href="/{{ lang.code }}/" class="btn btn-primary mx-2">
                        {{ lang.name_local }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
{#            <div class="cart mx-4">#}
{#                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-cart"#}
{#                     viewBox="0 0 16 16">#}
{#                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>#}
{#                </svg>#}
{#            </div>#}
        </div>
    </div>
</nav>