ecommerce/Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('product.urls', namespace='product')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('comments/', include('comments.urls', namespace='comments')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import ContactUsView
app_name = 'core'

urlpatterns = [
    path('about/', TemplateView.as_view(template_name='core/about.html'), name='about'),
    path('connect_us/', ContactUsView.as_view(), name='contact_us'),

]

ecommerce/orders/urls.py
from django.urls import path, include
from .api_urls import router
from .api_views import CartItemApiView
from .views import CartCheckOutView, PaymentView


app_name = 'orders'

urlpatterns = [
    path('api/', include(router.urls,),),
    path('api/cart_item/', CartItemApiView.as_view(), name='cart_item_api'),
    path('api/cart_item/<pk>', CartItemApiView.as_view(), name='detail_cart_item_api'),
    path('api/cart_item/<pk>/', CartItemApiView.as_view(), name='delete_cart_item'),
    path('api/cart_item/<pk>/', CartItemApiView.as_view(), name='update_cart_item'),

    path('cart/checkout/', CartCheckOutView.as_view(), name='cart_checkout'),
    path('cart/payment/', PaymentView.as_view(), name='cart_payment'),
]

ecommerce/product/urls.py
from django.urls import path, include
from .api_urls import router
from .views import *

app_name = 'product'

urlpatterns = [
    path('', LandingView.as_view(), name='landing'),
    path('product/<int:pk>/<slug:product_slug>', ProductDetailView.as_view(), name='product_detail'),
    path('category/<int:category_id>/<slug:category_slug>', CategoryDetailView.as_view(), name='category_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    # product api urls
    path('api/', include(router.urls)),

]

ecommerce/orders/models.py
from datetime import timedelta

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MinLengthValidator
from django.utils import timezone
from core.models import BaseModel, BaseDiscount
from django.db import models
from customers.models import Customer, Address
from product.models import Product
from product.models import Category
from django.utils.translation import gettext as _


class Cart(BaseModel):
    """
        A class used to implement carts

        attributes:

            total_price: a positive integer\n
            final_price: a positive integer\n
            off_code: foreign key to OffCode Model\n
            customer: foreign key to customer Model\n

        methods:
            total_worth: calculate sum of items prices without considering off code\n
            final_worth: calculate  sum of items prices *By considering* off code
    """
    total_price = models.PositiveIntegerField(default=0, verbose_name=_('Total Price'), null=True, blank=True)
    final_price = models.PositiveIntegerField(default=0, verbose_name=_('Final Price'), null=True, blank=True)
    off_code = models.OneToOneField('OffCode', on_delete=models.CASCADE, related_name='carts', null=True, blank=True,
                                    verbose_name=_('Off Code'))
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='carts', verbose_name=_('Customer'))
    address = models.ForeignKey(Address, on_delete=models.RESTRICT, related_name='carts', verbose_name=_('Address'),
                                null=True, blank=True)

    class Meta:
        verbose_name = _('Cart')
        verbose_name_plural = _('Carts')

    def total_worth(self):
        """
            calculate total price of cart
        :return: total price amount (int)
        """
        self.total_price = sum([item.product.final_price * item.count for item in self.items.all()])
        return self.total_price

    def final_worth(self):
        """
        calculate final price of cart e.g with considering discounts
        :return: final price (int)
        """
        total = self.total_worth()
        self.final_price = total - self.off_code.profit_value(total) if self.off_code else total
        return self.final_price

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        """
        save calculated prices in db
        """
        self.total_price = self.total_worth()
        self.final_price = self.final_worth()
        super().save(force_insert, force_update, using, update_fields)

    def update_inventory(self):
        """update products inventory of cart items """
        if self.items.all():
            for item in self.items.all():
                item.product.calculate_inventory(item.count)

    def get_profit(self):
        """
        calculate profit of cart
        """
        return self.total_worth() - self.final_worth() if self.off_code else 0


class CartItem(BaseModel):
    """
        A class used to implement cart items
    """

    count = models.PositiveIntegerField(default=1, verbose_name=_('Count'),
                                        validators=[MinValueValidator(1, message='minimum count is 1')])
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE, related_name='items', verbose_name=_('Cart'))
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name=_('Product'))

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def clean(self):
        """
        check and validate count to not be greater than product inventory
        :return:
        """
        if self.count > self.product.inventory:
            raise ValidationError('Maximum count is exceeded')

    def __str__(self):
        return f'{self.count} of {self.product}'


class OffCode(BaseDiscount):
    """
        A class to implement off codes
    """
    valid_from = models.DateTimeField(validators=[MinValueValidator(timezone.now(), _('must be greater than now'))],
                                      verbose_name=_('Valid From'))
    valid_to = models.DateTimeField(
        validators=[MinValueValidator(timezone.now() + timedelta(minutes=1), _('must be greater than now'))],
        verbose_name=_('Valid To'))
    code = models.CharField(max_length=50, verbose_name=_('Off Code'),
                            validators=[MinLengthValidator(5, _('must be more than five letters'))])

    @property
    def active(self):
        if self.valid_from < timezone.now() < self.valid_to:
            return True
        return False

    class Meta:
        verbose_name = _('Off Code')
        verbose_name_plural = _('Off Codes')

    def __str__(self):
        show = f"%{self.value}" if self.type == 'PER' else f"${self.value}"
        return show

ecommerce/orders/views.py
import time
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse, Http404
from django.shortcuts import redirect, get_object_or_404
from django.views import View
from django.views.generic import TemplateView
from django.utils.translation import gettext as _
from customers.forms import AddressRegisterForm
from customers.models import Address
from orders.models import Cart, OffCode


class CartCheckOutView(LoginRequiredMixin, TemplateView):
    template_name = 'orders/cart/cart.html'

    def setup(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.real_cart = Cart.objects.get(customer=request.user.customer, is_active=True)
        super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Cart Checkout')
        context['real_cart'] = self.real_cart
        return context

    def post(self, request):
        # print(request.POST)
        data = request.POST
        real_cart = self.real_cart

        # AJAX Post request for setting off code
        if data.get('action') == "set_offcode":
            code = data['offcode']
            offcode = get_object_or_404(OffCode, code=code)

            if offcode.active:
                self.real_cart.off_code = offcode
                self.real_cart.save()
                data = {'total_price': self.real_cart.final_worth(), 'offcode': str(offcode), 'code': offcode.code,
                        'valid_to': offcode.valid_to}

                return JsonResponse(data)
            # invalid off code
            raise Http404()

        # AJAX Post request for setting address
        elif data.get('action') == "set_address":
            address = get_object_or_404(Address, pk=data['address'])
            real_cart.address = address
            real_cart.save()
            return JsonResponse({'msg': f'Address {address.id} was set!'})

        # AJAX POST request for add new address
        elif data.get('action') == 'new_address':
            form = AddressRegisterForm(request.POST)
            if form.is_valid():
                new_address = form.save(commit=False)
                new_address.customer = request.user.customer
                new_address.save()
                return JsonResponse({'address_id': new_address.id, 'address': str(new_address)})
            return JsonResponse({'msg': form.errors}, status=400)


class PaymentView(LoginRequiredMixin, View):
    def get(self, request):
        real_cart = Cart.objects.get(customer=request.user.customer, is_active=True)

        if hasattr(real_cart, 'address') and real_cart.items.all():
            real_cart.deactivate()
            real_cart.save()
            real_cart.update_inventory()
            time.sleep(5)
            return redirect('product:landing')
        messages.error(request, _("you don't have any items!"), 'error cart')
        return redirect('orders:cart_checkout')

ecommerce/orders/templates/orders/cart/inc/address.html
{% load i18n %}
<div class="p-r-18 p-r-0-sm w-full-ssm">

    <div class="p-t-15">

         <div class="mtext-109 bg0 m-b-12">
            <span>Address:</span>
        </div>
        <!-- address select -->
        <div class="rs1-select2 rs2-select2 bor8 bg0 m-b-12 m-t-9">

            <select name="address" id="addresses" class="form-control">
                <option value="0">{% trans 'Select an address' %} ...</option>
                {% if request.user.customer.addresses.all %}
                    {% for address in request.user.customer.addresses.all %}
                        <option value="{{ address.id }}" {% if real_cart.address == address %}selected{% endif %}>{{ address }}</option>
                    {% endfor %}
                {% endif %}
            </select>

        </div>

        <div>
            <span class="font-weight-bold rounded p-2">
                {% trans 'Add New Address' %}
            </span>
            <hr>
        </div>

        <div class="bor8 bg0 m-b-12">
            <input class="stext-111 cl8 plh3 size-111 p-lr-15" type="text" name="state"
                   placeholder="{% trans 'State' %}">
        </div>
        <ul id="state_errors" class="text-danger"></ul>

        <div class="bor8 bg0 m-b-12">
            <input class="stext-111 cl8 plh3 size-111 p-lr-15" type="text" name="city"
                   placeholder="{% trans 'City' %}">
        </div>
        <ul id="city_errors" class="text-danger"></ul>

        <div class="bor8 bg0 m-b-22">
            <input class="stext-111 cl8 plh3 size-111 p-lr-15" type="text" name="postcode"
                   placeholder="{% trans 'Postcode / Zip' %}">
        </div>
        <ul id="postal_code_errors" class="text-danger"></ul>

        <div class="bor8 bg0 m-b-22">
            <textarea class="plh3 size-111 p-lr-15" type="text" name="address_detail"
                      placeholder="{% trans 'Address Detail' %}" cols="10" style="height: 100px;"></textarea>
        </div>
        <ul id="address_detail_errors" class="text-danger"></ul>

        <div class="flex-w">
            <div class="flex-c-m stext-101 cl2 size-115 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer" id="register_address">
                {% trans 'Register Address' %}
            </div>
        </div>

    </div>

</div>

ecommerce/orders/templates/orders/cart/inc/breadcrumb.html
{% load i18n %}
<div class="container mt-5">
    <div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
        <a href="{% url 'product:landing' %}" class="stext-109 cl8 hov-cl1 trans-04">
            {% trans 'Home' %}
            <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
        </a>

        <span class="stext-109 cl4">
            {% trans 'Cart' %}
        </span>
    </div>
</div>

ecommerce/orders/templates/orders/cart/inc/cart_js.html
{% load static %}
{% load i18n %}
<script>
    $(document).ready(function(){

        const notice = new Notice();
        // remove cart item btn event
        $('.removeItem-btn').on('click', (e)=>{
             e.preventDefault();
            let elem = $(e.target)
            let itemId = elem.parent().attr('data-itemId')
            let productName = $('#productName').text()

            console.log(`trying to delete ${productName} with id ${itemId}`)

            // beautiful alert
            swal({
                  title: "Are you sure?",
                  icon: "warning",
                  buttons: true,
                  dangerMode: true,
                })
            .then((willDelete) => {
                  if (willDelete) {
                    swal("done! item deleted!", {icon: "success",
                         timer: 1200,
                        buttons: false,
                    });
                    // on confirm delete item from cart
                    removeItemFromCart(elem)

                    } else {
                       swal("nice choice! item kept", {
                        icon: "success",
                         timer: 1200,
                         buttons: false,

                            });
                            }
                });
    });

        // send ajax request and delete from cart
        function removeItemFromCart(elem){

            let productId = elem.parent().attr('data-itemId')
            let countItemsIcon = +$('#cartIcon').attr('data-notify')
            let cartTotal = $('#cartTotal')
            let url = "{% url 'orders:delete_cart_item' 0 %}".replace('0', productId)

        // delete request for delete item from cart
        $.ajax({
                url: url,
                method: 'DELETE',
                headers: {
                    "X-CSRFToken": '{{ csrf_token }}',
                },
                success: function (data){
                    console.log(`on success delete request: ${data}`)

                    $('#cartBody').find(`[data-itemId="${data.item}"]`).remove();   // remove item from dynamic nav cart
                    elem.parents('tr').remove();        // remove item from main cart page
                    $('.cartIcon').attr('data-notify', countItemsIcon - 1);         // item count notification on nav bar
                    cartTotal.text(data.total_price)
                    $('.total_price').text(data.total_price)
                    let itemsCount = data.items_count
                    // hide purchase btn if cart is empty
                    if (Number(itemsCount) <= 0){
                        console.log(itemsCount)
                        $("#purchase").empty()
                    }
                },
                error: function (e){
                    console.log(e)
                },
            });

    }

        // add item count of cart btn event
        $('.increaseItem,.decreaseItem').on('click', function (e){
            e.preventDefault()
            notice.showLoading({
                title: 'Updating...',
                color: '#333',
                fontSize: 20,
                backgroundColor: 'rgba(255,255,255,.6)'
            });
            let itemId = $(this).attr('data-itemId')
            let cartTotal = $('#cartTotal')
            let productId = $(this).attr('data-productId')
            let currentValue = $(this).attr('class').includes("increaseItem") ?  $(this).prev("input.num-product") : $(this).next("input.num-product");

            if ($(this).attr('class').includes("decreaseItem") ) {
                if(currentValue.val() > 0 && (currentValue.val() - 1)!== 0){
                    currentValue.val(Number(currentValue.val()) - 1);
                // check for minimum count
                }else{
                    Toastify({
                        text: "{% trans 'Minimum value for count is 1' %}!",
                        duration: 1600,
                        stopOnFocus: true,
                        position: 'center',
                    style: {
                        background: "red",
                      }
                    }).showToast();
                    notice.hideLoading()
                    return 1
                }
            }else{
                currentValue.val(Number(currentValue.val()) + 1);
            }

            let url = "{% url 'orders:update_cart_item' 0 %}".replace('0', itemId)
            let countProductInNavCart = $(`#cartBody > li#${productId}`).find('.count-product-cart')
            let productInventory = currentValue.attr('max')
            let itemTotalPrice = $(this).parents("td").next('td').children('span')

            let productPrice = $(this).parents("td").prev('td').children('span')

            console.log('inventory: '+productInventory)
            if (Number(currentValue.val()) == Number(productInventory)) {
                $(this).hide()

                Toastify({
                        text: "{% trans 'maximum count!' %}!",
                        duration: 1600,
                        stopOnFocus: true,
                        position: 'center',
                    style: {
                        background: "red",
                      }
                    }).showToast();

            }else if (Number(currentValue.val()) < Number(productInventory)){
                currentValue.siblings(".increaseItem").html('<i class="fs-16 zmdi zmdi-plus"></i>')

                currentValue.siblings(".increaseItem").show()
            }
            console.log(`product Id is ${productId}`)
            console.log(`item Id is ${itemId}`)

            setTimeout(
              function()
              {
                // Patch request for partial update of cart item
                $.ajax({
                    url: url,
                    method: 'PATCH',
                    data: {
                        'item_id':itemId,
                        'count': currentValue.val(),
                    },
                    headers: {
                        "X-CSRFToken": '{{ csrf_token }}',
                    },
                    success: function (data){
                        console.log(`on success patch request: `, data.item)
                        notice.hideLoading()
                        countProductInNavCart.text(data.item.count)
                        let total = data.cart_total_price
                        cartTotal.text(total)
                        {#$('.total_price').text(data.cart_total_price)#}
                        $("#total_price").text(data.cart_total_price)
                        $("#final_price").text(data.cart_final_price)

                        itemTotalPrice.text(data.item.count * Number(productPrice.text()))

                    },
                    error: function (e){
                        notice.hideLoading()
                        Toastify({
                            text: JSON.parse(e.responseText).count[0],
                            duration: 1600,
                            stopOnFocus: true,
                            position: 'center',
                        style: {
                            background: "red",
                          }
                        }).showToast();

                        console.log(e)

                    },
                });

              }, 1100);
        });

        // set off code on click event of apply
        $('#add_offcode').on('click', function (){
        let offcode = $('#offcode_txt')

        // check if off code input already set
        if (offcode.attr('disabled') == 'disabled'){

            $(this).text('Apply Off code')
            $(this).attr('title', '')
            $(this).addClass('hov-btn3')
            offcode.prop('disabled', false);
            offcode.focus()
            return 1
        }else {
                let finalPrice = $("#final_price")
                let url = "{% url 'orders:cart_checkout' %}"
                let applyOffcode = $('#add_offcode')

                // check for empty input
                if (offcode.val() == ''){
            Toastify({
                        text: "{% trans 'please enter your off code' %}!",
                        duration: 3000,
                        close: true,
                        stopOnFocus: true,
                    }).showToast();
            return 1
        }

                $.post(
                    url,
                    {
                        "csrfmiddlewaretoken": "{{ csrf_token }}",
                        "action": 'set_offcode',
                        "offcode": offcode.val(),
                    },
                    function (data){
                        console.log(data)

                        Toastify({
                                text: "{% trans 'Off code applied!' %}!",
                                duration: 3000,
                                close: true,
                                stopOnFocus: true,
                            }).showToast();

                        offcode.val(data.code)
                        offcode.attr('title', 'is valid until '+ data.valid_to)
                        offcode.attr('disabled', 'disabled')
                        applyOffcode.text(data.offcode)
                        applyOffcode.attr('title', 'click to change')
                        applyOffcode.removeClass('hov-btn3')

                        finalPrice.text(data.total_price)
                    },
                    ).fail(function(error) {
                console.log(error)
                Toastify({
                        text: "{% trans 'Invalid Off code' %}!",
                        duration: 3000,
                        close: true,
                        stopOnFocus: true,
                    style: {
                        background: "red",
                      }
                    }).showToast();
            })
        }
        })

         // set Address on change of address selection event
        $("#addresses").on('change', function () {
            const url = "{% url 'orders:cart_checkout' %}";

        if ($(this).val() != "0"){         // first option that is : select an address
            // show payment btn
            elem = `<div class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer" id="purchase">
                                {% trans 'Proceed to Checkout' %}
                </div>`
            let itemsCount = "{{ real_cart.items.all.count }}"
            if (Number(itemsCount) > 0){
                $("#purchase").html(elem)
            }

            $.post(
                url,
                {
                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                    "action": 'set_address',
                    "address": $(this).val(),
                },
                function (data) {
                    console.log(data)
                    Toastify({
                        text: "{% trans 'Address was set' %}!",
                        duration: 3000,
                        close: true,
                        stopOnFocus: true,
                    }).showToast();
                },
            ).fail(function(error) {
                console.log(error)
                Toastify({
                        text: "{% trans 'Something went wrong!' %}!",
                        duration: 3000,
                        close: true,
                        stopOnFocus: true,
                    }).showToast();
            })
        }
    });

        // add new address on click event of register address btn
        $('#register_address').on('click', function () {
            $('#addresses').val('0')

            let stateName = $("input[name='state']").val()
            let cityName = $("input[name='city']").val()
            let postCode = $("input[name='postcode']").val()
            let addressDetail = $("textarea[name='address_detail']").val()

            let url = "{% url 'orders:cart_checkout' %}";
            elem = `<div class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer" id="purchase">
                                {% trans 'Proceed to Checkout' %}
                </div>`

         $.post(
                url,
                {
                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                    "action": 'new_address',
                    'state': stateName,
                    'city': cityName,
                    'postal_code': postCode,
                    'address_detail': addressDetail
                },
                function (data) {
                    console.log(data)
                       swal("done! new address saved!!", {icon: "success",
                         timer: 1200,
                        buttons: false,
                    });
                    $('#addresses').append(`<option value="${data.address_id}" selected>${data.address}</option>`)

                    $("#state_errors").empty()
                    $("#city_errors").empty()
                    $("#postal_code_errors").empty()
                    $("#address_detail_errors").empty()
                    $("#purchase").html(elem)

                },
            ).fail(function(error) {
                console.log(error)
                let errors = error.responseJSON.msg

                for (let i in errors){
                    item = $(`#${i}_errors`)
                    item.html(`<li style="list-style-type: disc;">${errors[i][0]}</li>`)

                }
         })
    })

        // click event for proceed to checkout btn
        $("#purchase").on('click', function () {
            swal("{% trans 'thank you for your choice' %}",{
                  title: "{% trans 'Payment successfully' %}",
                  icon: "success",
                  buttons: false,
                  timer: 3000,
                })
    })

    });
</script>

ecommerce/orders/templates/orders/cart/inc/cart_table.html
{% load core_extras %}
{% load i18n %}
<table class="table-shopping-cart">

    <!-- headers -->
    <tr class="table_head">
        <th class="column-1 text-center">{% trans 'Product' %}</th>
        <th class="column-2 text-center">{% trans 'Price' %}</th>
        <th class="column-3 text-center">{% trans 'Quantity' %}</th>
        <th class="column-4 text-center">{% trans 'Total' %}</th>
        <th class="column-5 text-center">{% trans 'Remove' %}</th>
    </tr>

    {% for item in cart %}

        <tr class="table_row" >
            <td class="column-1 text-center">
                <div class="how-itemcart1">
                    <img src="{{ item.product.pictures.first.picture.url }}" alt="{{ item.product.name }}"><br>
                </div>
                <!-- Product name -->
                <div class="text-left">
                    <a class="text-decoration-none" href="{{ item.product.get_absolute_url }}" data-id="{{ item.product.id }}" id="productName">{{ item.product.name }}</a>
                </div>

            </td>
            <td class="column-2 text-center">$ <span class="productPrice">{{ item.product.final_worth }}</span></td>
            <!-- product count -->
            <td class="column-3 text-center">
                <div class="wrap-num-product flex-w m-l-auto m-r-0">
                    <div class="cl8 hov-btn3 trans-04 flex-c-m decreaseItem" data-itemId="{{ item.id }}" data-productId="{{ item.product.id }}">
                        <i class="fs-16 zmdi zmdi-minus"></i>
                    </div>

                    <input class="mtext-104 cl3 txt-center num-product" type="number" name="num-product2" value="{{ item.count }}" max="{{ item.product.inventory }}" min="1">

                  {% if item.count < item.product.inventory %}
                         <div class="cl8 hov-btn3 trans-04 flex-c-m increaseItem" data-itemId="{{ item.id }}" data-productId="{{ item.product.id }}">
                            <i class="fs-16 zmdi zmdi-plus"></i>
                        </div>
                  {% endif %}

                </div>
            </td>
            <!-- total price of cart item -->
            <td class="column-4 text-center itemTotalPrice">$ <span>{{ item.product.final_worth|mul:item.count }}</span></td>
            <td class="column-5 text-center"><a href="" class="removeItem-btn" data-itemId="{{ item.id }}"><i class="fa fa-trash text-danger p-2 rounded" aria-hidden="true"></i></a></td>
        </tr>

    {% endfor %}

</table>

ecommerce/orders/templates/orders/cart/inc/finish_cart.html
{% load i18n %}
<div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
    <div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">

        <h4 class="mtext-109 cl2 p-b-30">
            {% trans 'Cart Totals' %}
        </h4>

        <div class="bor12 p-b-13">

            <div class="size-208">
                <span class="stext-110 cl2">
                   {% trans ' Total Price' %}:
                </span>
            </div>

            <div class="size-209">
                <span class="mtext-110 cl2">
                    $<span id="total_price" class="total_price">{{ cart.get_total_price }}</span>
                </span>
            </div>

        </div>

        <div class="flex-w flex-t bor12 p-t-15 p-b-30">

            <!-- address -->
            {% include 'orders/cart/inc/address.html' %}

        </div>

        <div class="flex-w flex-t p-t-27 p-b-33">

            <div class="size-208">
                <span class="mtext-101 cl2">
                    {% trans 'Final Price' %}:
                </span>
            </div>

            <div class="size-209 p-t-1">
                <span class="mtext-110 cl2 total_price" id="final_price">
                     ${{ real_cart.final_worth }}
                </span>
            </div>
        </div>


        <a href="{% url 'orders:cart_payment' %}" class="text-decoration-none text-light" id="purchase">
            {% if real_cart.address and real_cart.items.all %}

                <div class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer" id="purchase">
                                {% trans 'Proceed to Checkout' %}
                </div>
            {% endif %}
        </a>



    </div>
</div>